name: on pr changes

on:
  pull_request:

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: Get pr number
        id: pr_number
        run: |
          echo -n number= >> "$GITHUB_OUTPUT"
          echo "${{ github.ref }}" | cut -d/ -f3 >> "$GITHUB_OUTPUT"
      - name: hi
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr comment ${{ steps.pr_number.outputs.number }} --edit-last --create-if-none --body "Hi from GitHub CLI again!" --repo "${{ github.repository }}"
