name: on pr changes

on:
  pull_request:

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: Get pr number
        id: pr_number
        run: |
          echo -n number= >> "$GITHUB_OUTPUT"
          echo "${{ github.ref }}" | cut -d/ -f3 >> "$GITHUB_OUTPUT"
      - name: hi
        run: gh pr comment ${{ steps.pr_number.outputs.number }} --body "Hi from GitHub CLI"
