name: on pr changes

on:
  pull_request:

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: install tfplandoc
        run: |
          wget -O tfplandoc.zip https://github.com/Azure/tfplandoc/releases/download/v0.4.1/tfplandoc_0.4.1_linux_amd64.zip
          unzip tfplandoc.zip
          sudo mv tfplandoc_v0.4.1 /bin/tfplandoc
          type tfplandoc
      - name: Create comment file
        run: |
          echo "# Salutation" > comment.md
          echo "" >> comment.md
          echo "Hello from a md file ${{ github.sha }}" >> comment.md
      - name: Create comment from file
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          gh pr comment
          $(echo ${{ github.ref }} | cut -d/ -f3)
          --edit-last
          --create-if-none
          --body-file
          comment.md
          --repo
          "${{ github.repository }}"
