name: on pr changes

on:
  pull_request:

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: Get pr number
        id: pr_number
        run: >
          echo -n name= >> "$GITHUB_OUTPUT"
          echo "${{ github.ref }}" | cut -d/ -f3 >> "$GITHUB_OUTPUT"
