name: on push

on:
  workflow_dispatch:
    inputs:
      name:
        description: a name
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: echo -${{ inputs.name }}-