name: on push

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: create some random folder
        run: mkdir -p some/deep/level/folder
      - name: print cwd
        run: pwd
      - name: change dir
        run: |
          cd some/deep/level/folder
          pwd
      - name: print cwd
        run: pwd
        working-directory: some/deep/level/folder
