name: on push

on:
  workflow_dispatch:
    inputs:
      name:
        description: a name
        

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - 
        id: env_name
        run: |
          if [[ -z "${{ inputs.name }}" ]]; then
            echo ${{ github.ref_name }}
          else 
            echo ${{ inputs.name }}
          fi