name: on push

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: set variable
        id: name
        run: echo name=max >> "$GITHUB_OUTPUT"
      - run: echo -n ${{ steps.name.outputs.name }} | busybox hexdump -c
