name: on push

on:
  workflow_dispatch:
    inputs:
      name:
        description: "your name"
        type: string

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: echo "Hello ${{ inputs.name }}"
